[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build && cd ../backend && npm install"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
