[build]
builder = "nixpacks"
buildCommand = "npm --prefix ./frontend install && npm --prefix ./frontend run build && npm --prefix ./backend install"

[deploy]
startCommand = "npm --prefix ./backend start"
healthcheckPath = "/"
healthcheckTimeout = 100
